[package]
name = "bcc-sys"
version = "0.3.1"
authors = ["Zhiting Zhu <zhitingz@cs.utexas.edu>"]
description = "Rust binding to BPF Compiler Collection (BCC)"
keywords = ["bpf", "bindings"]
license = "Apache-2.0"
repository = "https://github.com/photoszzt/bcc-sys"
build = "build.rs"
readme = "README.md"

[build-dependencies]
bindgen = "0.31"
lazy_static = "0.2"
