[package]
name = "bcc-sys"
version = "0.1.0"
authors = ["Zhiting Zhu <zhitingz@cs.utexas.edu>"]
description = "Rust binding to BPF Compiler Collection (BCC)"
keywords = ["bpf", "bindings"]
license = "Apache-2.0"

[build-dependencies]
bindgen = "0.30.0"
lazy_static = "0.2.9"
